/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GsI18NConfigSchema {
  spreadsheet: {
    /**
     * Google Spreadsheet document ID
     */
    docId: string;
    /**
     * Specific sheet ID within the spreadsheet
     */
    sheetId: number;
    [k: string]: unknown;
  };
  googleServiceAccount: {
    email: string;
    privateKey: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
